config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :question_to_answers
  resources :answers
  resources :questions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question_to_answer.rb
class QuestionToAnswer < ApplicationRecord
  belongs_to :question
  belongs_to :answer
end

app/controllers/question_to_answers_controller.rb
class QuestionToAnswersController < ApplicationController
  before_action :set_question_to_answer, only: %i[ show edit update destroy ]

  # GET /question_to_answers or /question_to_answers.json
  def index
    @question_to_answers = QuestionToAnswer.all
  end

  # GET /question_to_answers/1 or /question_to_answers/1.json
  def show
  end

  # GET /question_to_answers/new
  def new
    @question_to_answer = QuestionToAnswer.new
  end

  # GET /question_to_answers/1/edit
  def edit
  end

  # POST /question_to_answers or /question_to_answers.json
  def create
    @question_to_answer = QuestionToAnswer.new(question_to_answer_params)

    respond_to do |format|
      if @question_to_answer.save
        format.html { redirect_to question_to_answer_url(@question_to_answer), notice: "Question to answer was successfully created." }
        format.json { render :show, status: :created, location: @question_to_answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question_to_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /question_to_answers/1 or /question_to_answers/1.json
  def update
    respond_to do |format|
      if @question_to_answer.update(question_to_answer_params)
        format.html { redirect_to question_to_answer_url(@question_to_answer), notice: "Question to answer was successfully updated." }
        format.json { render :show, status: :ok, location: @question_to_answer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question_to_answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_to_answers/1 or /question_to_answers/1.json
  def destroy
    @question_to_answer.destroy

    respond_to do |format|
      format.html { redirect_to question_to_answers_url, notice: "Question to answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question_to_answer
      @question_to_answer = QuestionToAnswer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_to_answer_params
      params.require(:question_to_answer).permit(:question_id, :answer_id)
    end
end

app/helpers/question_to_answers_helper.rb
module QuestionToAnswersHelper
end

app/views/question_to_answers/_form.html.erb
<%= form_with(model: question_to_answer) do |form| %>
  <% if question_to_answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question_to_answer.errors.count, "error") %> prohibited this question_to_answer from being saved:</h2>

      <ul>
        <% question_to_answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id %>
  </div>

  <div class="field">
    <%= form.label :answer_id %>
    <%= form.text_field :answer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/question_to_answers/edit.html.erb
<h1>Editing Question To Answer</h1>

<%= render 'form', question_to_answer: @question_to_answer %>

<%= link_to 'Show', @question_to_answer %> |
<%= link_to 'Back', question_to_answers_path %>

app/views/question_to_answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Question To Answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_to_answers.each do |question_to_answer| %>
      <tr>
        <td><%= question_to_answer.question_id %></td>
        <td><%= question_to_answer.answer_id %></td>
        <td><%= link_to 'Show', question_to_answer %></td>
        <td><%= link_to 'Edit', edit_question_to_answer_path(question_to_answer) %></td>
        <td><%= link_to 'Destroy', question_to_answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question To Answer', new_question_to_answer_path %>

app/views/question_to_answers/new.html.erb
<h1>New Question To Answer</h1>

<%= render 'form', question_to_answer: @question_to_answer %>

<%= link_to 'Back', question_to_answers_path %>

app/views/question_to_answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question_to_answer.question_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question_to_answer.answer_id %>
</p>

<%= link_to 'Edit', edit_question_to_answer_path(@question_to_answer) %> |
<%= link_to 'Back', question_to_answers_path %>